#! /bin/sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --experimental-backends &
wmname LG3D
dunst -conf $HOME/.config/dunst/dunstrc &
slstatus &
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xrandr --rate 60 &

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
