(()=>{"use strict";const e=globalThis,{chrome:t,browser:r}=e;let n,o,i,s;i=()=>{if(void 0!==n)return n;try{const e=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);e&&(n=parseInt(e[2]))}catch(e){}return n},s=()=>{if(void 0!==o)return o;try{o=-1!=navigator.userAgent.search(/Android|Mobile/)}catch(e){}return o};const a={FAST_EXEC_SUPPORT:!0,DETECT_CONSTRUCTORS_BY_KEYS:i()>=60,ALLOWS_FILE_SCHEME_ACCESS:!1,MAX_SCRIPTS:1e3,WEBREQUEST_XHR_SUPPORT:!0,WEBREQUEST_WEBSOCKET:!1,CAN_SAVEAS_ZIP:!0,
SHARED_OBJECT_URLS:!1,SHARED_BLOBS:!1,CONTEXT_MENU:!0,INCOGNITO_MODE:!0,FPI:!1,CLIPBOARD_API:!1},l=["chrome-extension:"];[].concat(["chrome"]);const c=(()=>{const e={getInternalPathRegexp:function(e,t){const r=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),n=l[0]+"//"+c.id+"/";return new RegExp(n.replace(r,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(r,"\\$1"))},getInternalPageRegexp:function(){return c.getInternalPathRegexp(!1,".html")},
getPlatformInfo:e=>t.runtime.getPlatformInfo(e),getBrowserInfo:e=>{e({name:"Chrome",version:`${i()}`,vendor:"unknown"})}};return Object.defineProperty(e,"lastError",{get:()=>t.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>t.runtime.id,enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>e.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4),enumerable:!0}),e})(),h=(()=>{let e;return Object.defineProperties({},{inIncognitoContext:{
get:()=>(void 0===e&&(e=t.extension.inIncognitoContext),e),set:t=>{e=t},enumerable:!0},...Object.getOwnPropertyDescriptors({getURL:function(e){return t.runtime.getURL(e)},sendMessage:(e,r)=>t.runtime.sendMessage(e,r),onMessage:{addListener:e=>t.runtime.onMessage.addListener(e)},connect:e=>t.runtime.connect({name:e})})})
})(),{AbortController:u,FileReader:f,TextDecoder:d,addEventListener:b,atob:p,btoa:m,clearInterval:g,clearTimeout:y,crypto:w,decodeURIComponent:E,encodeURIComponent:v,escape:A,location:U,removeEventListener:T,setInterval:R,setTimeout:_,unescape:O}=self;let{fetch:S}=self;const B=self,{DOMParser:I,Notification:C,Image:j,Worker:L,alert:P,confirm:D,document:N,localStorage:M,screen:x,webkitNotifications:Y}=(U.origin,U.host,self);let{XMLHttpRequest:k}=self,G=0;const H=[],W=()=>{
const e=["debug"],t=["log"],r=["warn","info"],n=["error"],o=[...e,...t,...r,...n],i=n;G>=80&&i.push(...e),G>=60&&i.push(...t),G>=30&&i.push(...r),o.forEach((e=>F[e]=i.includes(e)?console[e].bind(console):()=>{}))},F={set:e=>{G=e,H.forEach((e=>{e(F,G)})),W()},get:()=>G,get verbose(){return(F.debug||(()=>{})).bind(console)},debug:()=>{},log:()=>{},warn:()=>{},info:()=>{},error:()=>{},addChangeListener:e=>{H.push(e)}};W();let J=[];const K={},X={},$={},q=e=>{const t=(()=>{let e,t
;const r=[],n=[],o=e=>{n.push(e),i()},i=()=>{if(void 0!==e){let r;for(;n.length;)r=n.shift(),void 0!==r.state&&r.state!==e||"function"==typeof r.f&&r.f.call(s,t)}},s={promise:()=>s,done:e=>(o({state:!0,f:e}),s),fail:e=>(o({state:!1,f:e}),s),always:e=>(o({f:e}),s),progress:e=>(e&&r.push(e),s),then:(e,r,n)=>q((o=>{const i=(e,r)=>(...n)=>{const i=e?e(t):void 0,s=i&&"function"==typeof i.promise?i.promise():null,a=i&&"function"==typeof i.then?i:null
;if(s)s.done((e=>o.resolve(e))).fail(((...e)=>o.reject(e[0]))).progress(((...e)=>o.notify(...e)));else if(a)a.then(((...e)=>o.resolve(...e)),(e=>o.reject(e)));else{const t=e?[i]:n;o[r](t[0])}};s.done(i(e,"resolve")),s.fail(i(r,"reject")),s.progress(i(n,"notify"))})).promise(),each:e=>{const t=q();return s.then((r=>{const n=Array.isArray(r)?r:[r];q.when(n.map((t=>e(t)))).then(t.resolve)})),t.promise()},iterate:e=>{const t=q();return s.then((r=>{const n=(Array.isArray(r)?r:[r]).map((t=>()=>e(t)))
;q.onebyone(n,!0).done((e=>{t.resolve(e)})).fail(t.reject)})),t.promise()}};return{get:()=>s,try_resolve:r=>(void 0===e&&(e=!0,t=r),i(),s),try_reject:r=>(void 0===e&&(e=!1,t=r),i(),s),do_notify:e=>((e=>{r.forEach((t=>t(e)))})(e),s)}})(),r={promise:()=>t.get(),resolve:e=>t.try_resolve(e),reject:e=>t.try_reject(e),notify:e=>t.do_notify(e),
consume:e=>(e&&e.promise?e.promise().done((e=>r.resolve(e))).fail(((...e)=>r.reject(e[0]))).progress((e=>r.notify(e))):e&&e.then?e.then((e=>r.resolve(e)),((...e)=>r.reject(e[0]))):F.warn("promise: incompatible object given to consume()",e),r.promise())};return e&&e(r),r};q.Pledge=(...e)=>{const t=q();return t.resolve(...e),t.promise()},q.Breach=(...e)=>{const t=q();return t.reject(e[0]),t.promise()},q.onebyone=(e,t=!0)=>{const r=[],n=q();let o=0;const i=()=>{if(o<e.length){const s=(0,e[o++])()
;s&&s.promise?s.promise().done((e=>{r.push(e),i()})).fail((()=>{if(r.push(null),t)return n.reject();i()})):s&&s.then?s.then((e=>{r.push(e),i()}),(()=>{if(r.push(null),t)return n.reject();i()})):(r.push(s),i())}else n.resolve(r)};return i(),n.promise()},q.or=e=>{let t;const r=q(),n=()=>{e.length?(t=e.shift(),t&&q.Pledge().then(t).done(r.resolve).fail(n)):r.reject()};return n(),r.promise()},q.sidebyside=e=>{e=Array.isArray(e)?e:[e];const t=q();let r=e.length;return r?e.forEach((e=>{
e&&e.promise&&e.promise().always((()=>{0==--r&&t.resolve()}))})):t.resolve(),t.promise()},q.when=e=>{e=Array.isArray(e)?e:[e];const t=q();let r=e.length;const n=[];return r?e.forEach((e=>{let o;if(e&&e.promise)o=e.promise();else{if(!e.then)return void F.warn("promise: incompatible object given to when()",e);o=e}o.fail((()=>{t.reject(),r=-1})).done((e=>{n.push(e),0==--r&&t.resolve(n)}))})):t.resolve(n),t.promise()},Object.defineProperties(Promise.prototype,{done:{value:function(e){
return this.then(((...t)=>e.apply(this,t)))},configurable:!0,enumerable:!0,writable:!1},fail:{value:function(e){return this.then((()=>{}),((...t)=>e.apply(this,t)))},configurable:!0,enumerable:!0,writable:!1},always:{value:function(e){return this.then(((...t)=>e.apply(this,t)),((...t)=>e.apply(this,t)))},configurable:!0,enumerable:!0,writable:!1}});const z=Promise;let V=0;const Z=async function(e,...t){await(()=>{const e=Date.now();if(V+1e3<e)return new z((e=>_((()=>{V=Date.now(),e()}),0)))})(),
e.apply(this,t)},Q=function(e,t){return t?_.apply(this,[e,t]):(Z.apply(this,[e]),0)};var ee;!function(e){e.TESTING="TESTING",e.AUDIO_PLAYBACK="AUDIO_PLAYBACK",e.IFRAME_SCRIPTING="IFRAME_SCRIPTING",e.DOM_SCRAPING="DOM_SCRAPING",e.BLOBS="BLOBS",e.DOM_PARSER="DOM_PARSER",e.USER_MEDIA="USER_MEDIA",e.DISPLAY_MEDIA="DISPLAY_MEDIA",e.WEB_RTC="WEB_RTC",e.CLIPBOARD="CLIPBOARD",e.LOCAL_STORAGE="LOCAL_STORAGE",e.WORKERS="WORKERS",e.BATTERY_STATUS="BATTERY_STATUS",e.MATCH_MEDIA="MATCH_MEDIA",
e.GEOLOCATION="GEOLOCATION"}(ee||(ee={})),new class{constructor(e=1){if(this.waiting=[],e<0)throw new Error("Count must not be negative");this._count=e}acquire(){if(this._count>0)return this._count--,q.Pledge();{const e=q();return this.waiting.push(e.resolve),e.promise()}}release(){if(this.waiting.length>0){const e=this.waiting.shift();e&&e(void 0)}else this._count++}get count(){return this._count}}(1);const te=e=>{if(!I)throw new Error("DOMParser not available")
;return(new I).parseFromString(e,"text/xml")},re=e=>{var t;let r;return e&&(r=(null===(t=e.firstChild)||void 0===t?void 0:t.nextSibling)?e.firstChild.nextSibling:e.firstChild),r},ne=(e,t)=>{let r,n;if((r=e.getElementsByTagNameNS("*",t)[0])&&(n=r.firstChild))return n.nodeValue||void 0},oe=(e,t)=>{try{let r;r="object"==typeof t?t.encoding:t,r&&"utf-8"==r.toLowerCase()&&(e=O(v(e)));const n=new Uint8Array(e.length);for(let t=0;t<e.length;t++)n[t]=255&e.charCodeAt(t);return n.buffer}catch(e){
F.warn(e)}return new Uint8Array(0).buffer},ie=e=>{let t;t=e.split(",")[0].includes("base64")?p(e.split(",")[1]):O(e.split(",")[1]);const r=e.split(",")[0].split(":")[1].split(";")[0],n=new Uint8Array(t.length);for(let e=0;e<t.length;e++)n[e]=t.charCodeAt(e);return new Blob([n],{type:r})},se=e=>new Promise((t=>{const r=new f;r.onload=e=>{var r;t((null===(r=e.target)||void 0===r?void 0:r.result)||void 0)},r.readAsDataURL(e)})),{SHARED_OBJECT_URLS:ae,SHARED_BLOBS:le}=a;var ce;!function(e){
e[e.OBJ_URL=1]="OBJ_URL",e[e.BLOB=2]="BLOB",e[e.DATA_URI=4]="DATA_URI",e[e.BINARY=8]="BINARY"}(ce||(ce={}));const he=(ae?ce.OBJ_URL:0)+(le?ce.BLOB:0)+0+ce.BINARY,ue=e=>void 0!==e.objUrl,fe=e=>void 0!==e.blob,de=e=>void 0!==e.dataUri,be=e=>void 0!==e.binary;class pe{constructor(e,t){if(ue(e))this.objUrl=e.objUrl.url,this.type=e.objUrl.type;else if(fe(e))this.blob=e.blob;else if(de(e))this.dataUri=e.dataUri;else{if(!be(e))throw new Error("incompatible TransferableData");this.binary=e.binary}
this.kinds=t||he}dispose(){this.objUrl&&URL.revokeObjectURL(this.objUrl)}async toTransferableData(){if(this.kinds&ce.OBJ_URL){if(!this.objUrl&&(!this.blob&&this.dataUri&&(this.blob=ie(this.dataUri)),this.blob&&(this.objUrl=URL.createObjectURL(this.blob)),!this.objUrl))throw new Error("incomplete Transferable");return{objUrl:{url:this.objUrl,type:this.type}}}if(this.kinds&ce.BLOB){
if(!this.blob&&(this.objUrl?this.blob=await S(this.objUrl).then((e=>e.blob())):this.dataUri&&(this.blob=ie(this.dataUri)),!this.blob))throw new Error("incomplete Transferable");return{blob:this.blob}}if(this.kinds&ce.DATA_URI){if(!this.dataUri){let e=this.blob;if(!e&&this.objUrl&&(e=await S(this.objUrl).then((e=>e.blob()))),e&&(this.dataUri=await se(e)),!this.dataUri)throw new Error("incomplete Transferable")}return{dataUri:this.dataUri}}if(this.kinds&ce.BINARY){if(!this.binary){let e=this.blob
;if(!e&&this.objUrl&&(e=await S(this.objUrl).then((e=>e.blob()))),e&&(this.binary=await(async e=>new Promise((t=>{const r=new f;r.onload=()=>{t(r.result||"")},r.onerror=e=>{F.warn(`unable to decode data ${e}`),t("")},r.readAsBinaryString(e)})))(e)),!this.binary)throw new Error("incomplete Transferable")}return{binary:this.binary,type:"application/octet-stream"}}throw new Error("incompatible Transferable")}get tryObjectUrl(){return this.objUrl}get tryBlob(){return this.blob}get tryDataUri(){
return this.dataUri}get tryBinary(){return this.binary}async toBlob(){if(this.blob)return this.blob;if(!this.objUrl){if(this.dataUri)return ie(this.dataUri);if(this.binary)return new Blob([oe(this.binary)],{type:"application/octet-stream"});throw new Error("incompatible Transferable")}try{return await(await S(this.objUrl)).blob()}catch(e){return}}async toDataUri(){if(this.dataUri)return this.dataUri;{const e=await this.toBlob();if(!e)throw new Error("incompatible Transferable")
;return await se(e)}}static fromTransferableData(e){return e&&(fe(e)||ue(e)||de(e)||be(e))?new pe(e):void 0}}const me=(e=>{const t=[],r=[],n=()=>{let o;if(r.length<e.threads&&t.length&&(o=t.shift())){const e=o.fn();let t;if(void 0!==e.catch){const r=q();e.then(r.resolve).catch(r.reject),t=r.promise()}else t=e;r.push(t),t.always((()=>{let e;(e=r.indexOf(t))>-1&&r.splice(e,1),n()})),o.p.consume(t)}};return{add:function(e){const r=q();return t.push({fn:e,p:r}),n(),r.promise()}}})({threads:3})
;let ge=()=>{const e=q();return(t=>{const r="string"==typeof t?[t]:t,n=()=>{r.every((e=>!!$[e]))?(ge=q.Pledge,e.resolve()):J.push(n)};r.forEach((e=>{if(void 0===$[e]&&void 0===K[e]){const t=_((()=>{X[e]||(delete K[e],(e=>{X[e]=!0})(e),((e,t)=>{let r=1;const n=()=>{0==--r&&t&&t()};("string"==typeof e?[e]:e).forEach((e=>{r++;try{!function(e,t){{const r=document.createElement("script");r.setAttribute("src",e),t&&(r.onload=()=>t(!0),r.onerror=()=>t(!1)),
(document.head||document.body||document.documentElement||document).appendChild(r)}}(e,(t=>{t||F.warn("registry: self.load "+e+" failed! "),n()}))}catch(t){F.warn("registry: self.load "+e+" failed! ",t),n()}})),n()})(h.getURL(e+".js"),(()=>{(e=>{if(!$[e]){let t;$[e]=!0,delete X[e],(t=K[e])&&t(),(()=>{const e=J;J=[];for(const t of e)t()})()}})(e)})))}),0);K[e]=()=>{y(t),delete K[e]}}})),n()})(["vendor/saveas/filesaver"]),e.promise()};h.onMessage.addListener(((e,t,r)=>{
const{target:n,method:o,request:i}=e;if("offscreen"===n&&"offscreen"===o){let e=!1;if((async(e,t)=>{const{action:r}=e;if("download"===r){const{details:r,id:n}=e,{name:o,tfd:i}=r,s=pe.fromTransferableData(i),a=s&&await s.toBlob();if(!a)return console.warn("downs: invalid transferable"),void t({result:{id:n,error:"not_supported"}});ge().then((async()=>{const e=B.saveAs;return e?me.add((async()=>{e(a,o),await(500,new z((e=>Q(e,500)))),t({result:{id:n}})})):(t({result:{id:n,error:"failed"}}),
void console.warn("Unable to load saveAs!"))}))}else{const{doc:n}=e;if("xmlToWebdavResults"===r){const e=await(async e=>{if(I){const t=te(e);let r;if(!t||!(r=re(t))||!r.childNodes)return;return(async e=>{const t=[],r=e.getElementsByTagNameNS("*","response");for(let e=0;e<r.length;e++){const n=r[e];let o=ne(n,"href");if(null==o)continue;o=o.replace(/\/$/,"")
;const i=n.getElementsByTagNameNS("*","propstat")[0].getElementsByTagNameNS("*","prop")[0],s=ne(i,"getlastmodified"),a=ne(i,"getetag"),l=parseInt(ne(i,"getcontentlength")||"");if(i.getElementsByTagNameNS("*","resourcetype")[0].getElementsByTagNameNS("*","collection")[0]);else{const e={etag:a,name:o,id:o,modifiedTime:new Date(s||0).getTime(),size:l>=0?l:void 0,removed:-1==l};t.push(e)}}return t})(r)}throw new Error("DOMParser not available")})(n);t({result:e})}else if("xmlToCursor"===r){
const e=await(async e=>{if(I){const t=te(e);let r;if(!t||!(r=re(t))||!r.childNodes)return;return(e=>ne(e,"td:cursor"))(r)}throw new Error("DOMParser not available")})(n);t({result:e})}else if("xmlToResponseCodes"===r){const e=await(async e=>{if(I){const t=te(e);if(!t)return;return(e=>{var t;let r,n,o,i
;if((r=e.childNodes[0])&&(n=r.getElementsByTagNameNS("*","status")[0])&&(o=null===(t=n.firstChild)||void 0===t?void 0:t.nodeValue)&&(i=o.match(/HTTP\/[0-9.]+ ([1-5][0-9][0-9])/)))return[parseInt(i[1])]})(t)}throw new Error("DOMParser not available")})(n);t({result:e})}else console.warn("offscreen: unknown action",r),t({error:"unknown_action"})}})(i,(t=>{e=!0,r(t)})),!e)return!0}}))})();