this.pagejs=e=>{(()=>{"use strict";const t="vault"in e;if(t&&void 0===e.vault)throw"Invalid vault";const n=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.assign,r=Object.getOwnPropertyDescriptor,s=e=>o({__proto__:null},e);return s({sourceWindow:e,cSO:s,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,
O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:Object.getPrototypeOf,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,
R_r:r(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,
USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,
E_rA:Element.prototype.removeAttribute,D_cS:r(Document.prototype,"currentScript").get,D_gRS:r(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:r(MouseEvent.prototype,"relatedTarget").get,C_d:r(CustomEvent.prototype,"detail").get,C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,
MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,
createElement:e.Document.prototype.createElement})
})(e.unsafeWindow),{cSO:o,F_c:r,F_a:s,F_b:a,F_tS:i,A_fE:c,A_so:l,A_sh:d,A_j:u,A_iO:g,A_iA:p,O_a:m,O_k:f,O_v:v,O_dP:_,O_dPy:b,O_hOP:h,O_gOPN:M,O_gOPD:y,O_gOPDs:w,O_gPO:E,O_tS:S,J_p:R,J_s:G,M_f:L,M_r:I,M_m:O,M_mi:C,N_tS:x,N_MSI:P,P_t:k,P_c:T,R_rABS:D,R_rAT:A,R_r:U,R_enq:$,R_cl:j,S_fCC:F,S_sl:V,S_su:N,S_iO:q,S_sp_nr:X,S_tr:B,S_rA_nr:H,S_cCA:W,S_tLC:K,S_tUC:J,Y_tST:z,D_pFS:Y,D_cS:Q,D_gRS:Z,D_cE:ee,D_gEBT:te,E_r:ne,E_s:oe,E_rA:re,C_pA:se,M_d:ae,C_d:ie,M_rT:ce,U_cOU:le,U_rOU:de,USP_tS:ue,X_o:ge,X_s:pe,X_pSD:me,X_pSH:fe,X_pSL:ve,X_pSO:_e,X_pSU:be,D_n:he,I_tS:Me,W_aEL:ye,W_rEL:we,parseInt:Ee,parseFloat:Se,console:Re,encodeURIComponent:Ge,decodeURIComponent:Le,encodeURI:Ie,decodeURI:Oe,escape:Ce,unescape:xe,atob:Pe,btoa:ke,postMessage:Te,dispatchEvent:De,alert:Ae,prompt:Ue,confirm:$e,close:je,getElementById:Fe,createEvent:Ve,createElement:Ne,CustomEvent:qe,CompositionEvent:Xe,KeyboardEvent:Be,MouseEvent:He,MutationObserver:We,Uint8Array:Ke,FileReader:Je,DOMParser:ze,XMLHttpRequest:Ye,Function:Qe,RegExp:Ze,Promise:et,Blob:tt,ReadableStream:nt,Number:ot,String:rt,Proxy:st,Window:at}=n,it=r,ct=s,lt=f,dt=v,ut=m,gt=_,pt=b,mt=M,ft=y,vt=E,_t=w||(e=>{
const t=Et({});for(const n in e)t[n]=ft(e,n);return t}),bt=p,ht=L,Mt=I,yt=O,wt=(e,t,n)=>it(ct,e,t,n),Et=o,St=(e,t,n)=>(pt(e,t,Et({value:n,configurable:!0,enumerable:!0,writable:!0})),e),Rt=(e,t)=>qt(e,t)?e[t]:void 0,Gt=(e,t)=>{const n=ft(e,t);return n?Et(n).value:void 0},Lt=(e,t)=>{const n=(e,t,o)=>{const r=ft(e,t),s=r?Et(r):void 0;let a;return s?s.enumerable?s.value:void 0:--o>=0&&(a=vt(e))?n(a,t,o):void 0};return n(e,t,5)},It=e=>{const t=(t,...n)=>wt(e,t,n);return St(t,"wrappedJSObject",e),t
},Ot=()=>e=>It(e),Ct=It(a),xt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const r=typeof e;if("object"===r){if(n){if(-1!=Vt(n,e))throw"Converting circular structure to JSON";St(n,n.length,e)}else n=[e];if(bt(e)){let r="";for(let o=0;o<e.length;o++){let s;s=qt(e,o)?Rt(e,o):Lt(e,o);const a=t(s,n);r+=`${o?",":""}${void 0===a?"null":a}`}o=`[${r}]`}else{let r="";Nt(lt(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${G(o)}: ${s}`)})),o=`{${r}}`}n.length-=1}else{
if("bigint"===r)throw"Do not know how to serialize a BigInt";o=G(e)}}return o};return t(e)},Pt=e=>{const t=R(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)St(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(bt(e))return n(e);{const t={};return Nt(lt(e),(r=>{const s=e[r];let a;a="object"==typeof s?bt(s)?n(s):o(s):s,St(t,r,a)})),t}}return e};return o(t)},kt=Ot()(l),Tt=(e,t,n,...o)=>{const r=o||[],s=Ut(e,0,t),a=Ut(e,t,n),i=Ut(e,t+n);let c=jt([],s);return c=jt(c,r),
c=jt(c,i),Et({result:c,removed:a})},Dt=Ot()(d),At=(e,t)=>{const n=[];return Nt(e,(e=>{t(e)&&Ft(n,e)})),n},Ut=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=yt(0,o+r));let s=void 0===n?o:n;s<0&&(s=yt(0,o+s)),s>o&&(s=o);const a=Et({});for(let t=r;t<s;t++)a[t]=Gt(e,t);return dt(a)},$t=Ot()(u),jt=(e,...t)=>{let n=e.length;const o=Et(e);for(let e=0;e<t.length;e++){const r=t[e],s=bt(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=Gt(s,e);n+=s.length}return dt(o)},Ft=(e,t)=>{
let n=e.length||0;return St(e,n,t),n++,e.length=n},Vt=Ot()(g),Nt=Ot()(c),qt=Ot()(h),Xt=Ot()(X),Bt=Ot()(V),Ht=It(S),Wt=vt({}),Kt=e=>{const t=Et(e),n=mt(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&vt(r)===Wt&&(t[o]=Kt(r))}return t},Jt=e=>{const t=Xt(Ht(e)," ");return Bt($t(Ut(t,1)," "),0,-1)},zt=(Ot()(i),
Ot()(x)),Yt=P,Qt=Ot()(k),Zt=Ot()(T),en=Ot()(D),tn=Ot()(A),nn=Ot()(U),on=$?Ot()($):$,rn=j?Ot()(j):j,sn=F,an=Ot()(N),cn=Ot()(q),ln=Ot()(B),dn=(Ot()(H||function(e,t){return $t(Xt(this,e),t)}),Ot()(W)),un=Ot()(K),gn=Ot()(J),pn=z,mn=It(Y),fn=It(Q),vn=It(Z),_n=(It(ee),It(te),It(ne)),bn=It(oe),hn=It(re),Mn=se,yn=It(ce),wn=It(ie),En=(ae&&Ot()(ae),It(ue)),Sn=(Ot()(ge),me),Rn=fe,Gn=ve,Ln=_e,In=be,On=(Ot()(pe),he),Cn=st,xn=ot,Pn=qe,kn=Be,Tn=He,Dn=Ke,An=We,Un=tt,$n=function(e,t){return Gt(e,t)},jn=Et({
addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,Promise:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Fn=(()=>{const e=Et({getElementById:Fe,createEvent:Ve,createElement:Ne,dispatchEvent:De,addEventListener,removeEventListener}),t=Et({});return Nt(lt(e),(n=>{try{const o=e[n];t[n]=function(...e){return wt(o,qn.document,e)}
}catch(e){t[n]=((e,t)=>{if(Bn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}})),t})(),Vn=Et({top:!0,location:!0}),Nn=e,{unsafeWindow:qn,unsafeThis:Xn}=Nn;e.bridges=e.bridges||Et({});const Bn=e.console=e.console||Et({}),Hn=Et({addEventListener:Ct(ye,qn),removeEventListener:Ct(we,qn)});Nt(lt(Vn),(async e=>{if(!Hn[e])try{const t=qn[e];if(null==t)return;Hn[e]=t}catch(e){}})),
Nt(lt(jn),(async e=>{if(!Hn[e])try{let t=Gt(qn,e);if(void 0===t&&(Xn===qn||void 0===(t=Gt(Xn,e))))return;const n=jn[e];Hn[e]=!1===n&&"function"==typeof t?Ct(t,Xn):t}catch(e){}}));const Wn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Nt(t,(t=>t(e)))}else t=e;o=!0}}));const r=Et({then:e=>(o?e(t):Ft(n,e),r)});return r},Kn=()=>zt(On()+19831206*Mt()+1,36),Jn=async e=>{await null,e()},zn=()=>{const e=fn(qn.document);e&&(hn(e,"nonce"),_n(e))},Yn=(()=>{
const{console:t,bridges:n}=e,o=Et({});let r;const s=(e,n,r,s)=>{let i,c=[],l=[],d=[],u=[];const g=()=>{l=[],d=[],u=[],v(),y=null,delete o[n]},p=t=>{e.send("port.message",Et({response_id:n,value:t}))},m=e=>{s&&"messageId"in e&&Ft(c,e),p(e)},f=(e,t=!0)=>{i=e,t&&p(e)},v=()=>{i=void 0},_=Et({addListener:e=>{Ft(l,e)}}),b=Et({addListener:e=>{Ft(d,e)}}),h=Et({addListener:e=>{Ft(u,e)}}),M=()=>{g(),e.send("port.message",Et({response_id:n,disconnect:!0}))};let y=Et(r?{postMessage:m,connectMessage:f,
stopReconnecting:v,onMessage:_,onDisconnect:b,onReconnect:h,disconnect:M}:{postMessage:m,onMessage:_,onDisconnect:b,disconnect:M});return o[n]=Et({message:e=>{if(s&&(e=>"ack"in e)(e)){const{messageId:n}=e;(e=>{if(!e)return void t.warn("PortMessaging: no message id in ack message");if(i&&i.messageId===e)return;let n=-1;kt(c,((t,o)=>t.messageId===e&&(n=o,!0))),-1!==n?(Nt(Ut(c,0,n),(e=>t.warn(`PortMessaging: message ${e.messageId} was not ack'ed!`,e))),
c=Ut(c,n+1)):t.warn(`PortMessaging: no one is waiting for ${e}`)})(n)}l&&Nt(l,(t=>t(e)))},disconnect:()=>{if(i&&r)return a(r,n),f(i),s&&Nt(c,(e=>p(e))),void(u&&Nt(u,(e=>e())));d&&Nt(d,(e=>e())),g()}}),y},a=(e,t)=>{n.first.send("port.message",Et({response_id:t,connect:!0,destination:e}))};return Et({message:(e,n)=>{let a;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(n,e.response_id))}else{if(!e.response_id)throw"invalid message"
;if(!(a=o[e.response_id]))return void t.warn("ports: unknown id",e.response_id,e);e.disconnect?a.disconnect():a.message(e.value)}},connect:function(e,t,o){const r=Kn();return a(e,r),s(n.first,r,t?e:void 0,o)},onConnect:Et({addListener:e=>{r=e}})})})(),{bridges:Qn}=e,Zn=Et({}),eo=Et({});let to=!0,no=[];Jn((()=>{to=!1,Nt(no,(({m:e,i:t})=>Qn.first.send("console",[e,t]))),no=[]})),Nt(["debug","log","info","warn","error"],(e=>{St(Zn,e,((...t)=>{const n=(e=>{const t=[];return Nt(e,(e=>{
Ft(t,(e=>xt(e))(e))})),t})(t);if(to)return Ft(no,Et({m:e,i:n}));Qn.first.send("console",[e,n])}))}));const oo=Et(_t(qn.console)),ro=Et({});Nt(mt(Re),(e=>{const t=Et(oo[e]);ro[e]=Et({get:"value"in t?()=>t.value:t.get,enumerable:!0,configurable:!1})})),gt(eo,ro)
;const so=["chrome"],ao=["GM.backgroundControl"],io=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],co=["GM_cookie","GM.cookie"],lo=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener","GM_setValue","GM.setValue","GM_deleteValue","GM.deleteValue"],uo=["GM_download","GM.download"],go=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],po=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],mo=["GM_log","GM.log"],fo=["GM_notification","GM.notification"],vo=["GM_openInTab","GM.openInTab"],_o=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],bo=["GM_setClipboard","GM.setClipboard"],ho=["GM_xmlhttpRequest","GM.xmlHttpRequest"],Mo=["window.close"],yo=["window.focus"],wo=["window.onurlchange"],Eo=["GM_webRequest","GM.webRequest"],So=Et({
encode:e=>xe(Ge(e)),decode:e=>Le(Ce(e))}),Ro=Et({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=sn(255&dn(e,n));return ke(t)},decode:e=>Pe(e)}),Go=e=>{const t=new Dn(e.length);for(let n=0;n<e.length;n++)t[n]=dn(e,n);return t.buffer},Lo=(e,t)=>Wn((n=>{const o=new Hn.FileReader;o.onload=()=>{n(nn(o))},o.onerror=e=>{Bn.warn(`unable to decode data ${e}`),n("")},t?tn(o,e,t):en(o,e)})),{bridges:Io}=e;let Oo=0,Co=0;const xo=Et({}),Po=Et({}),ko=function(e,t,n,o){const r=()=>{xo[n]&&(wt(e,this,o),
delete xo[n])};"function"==typeof e&&(xo[n]=e,0===t?Jn((()=>r())):Io.first.send("setTimeout",Et({t:t||1}),(()=>r())))},To=function(e,t,n,o){if("function"==typeof e){const r=Po[n]=Yn.connect("setInterval");r.onMessage.addListener((()=>{Po[n]&&wt(e,this,o)})),r.onDisconnect.addListener((()=>Do(n))),r.postMessage(Et({method:"setInterval",t:t||1}))}},Do=e=>{const t=Po[e];t&&(t.disconnect(),delete Po[e])},Ao=(e,t,...n)=>{const o=Kn();return ko(e,t,o,n),o},Uo=e=>{(e=>{delete xo[e]})(e)
},$o=e=>Do(e),jo=(e,t,...n)=>{const o=++Co;return t=yt(t,1),ko(e,t,o,n),o},Fo=(e,t,...n)=>{const o=++Oo;return t=yt(t,1),To(e,t,o,n),o};let Vo;const No=e=>{if(void 0===Vo){Vo=!0;const t="keepAlive",n=Yn.connect(t,!0),o=Hn.location.href;n.onMessage.addListener((()=>{})),n.connectMessage(Et({messageId:Kn(),method:t,id:e,url:o})),n.onDisconnect.addListener((()=>{r&&$o(r),r=null}));let r=((e,t,...n)=>{const o=Kn();return To(e,t,o,n),o})((()=>{Vo?n.postMessage(Et({messageId:Kn(),method:"keepAlive",
url:o})):r&&(n.disconnect(),$o(r),r=null)}),2e4)}},qo=t=>{const{contextId:n,bridges:o}=e,r=Et({}),s=(e,t)=>kt(t,(t=>-1!=Vt(e,t))),a=e=>function(){const t=(async e=>e)(wt(e,this,arguments));return St(t,"then",(e=>Qt(t,e))),St(t,"catch",(e=>Zt(t,e))),t},i=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)Ft(o,$n(n,e)||void 0);return new Hn.Promise((t=>{wt(e,this,jt(o,[t]))}))},c=(e,t)=>{let n;const o=new Hn.Promise(((o,r)=>{const s=Et({}),a=t.onload,i=t.ontimeout,c=t.onerror
;Nt(lt(t),(e=>{s[e]=t[e]})),s.onerror=function(e){c?(o(e),wt(c,this,arguments)):r(e)},s.ontimeout=function(e){i?(o(e),wt(i,this,arguments)):r(e)},s.onload=function(e){o(e),a&&wt(a,this,arguments)};const l=e(s).abort;!0===n?l():n=l}));return St(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return Et({of:e=>{const l=e.script,d=(()=>{const e=s(l.grant,bo),t=(e,t,r)=>{o.first.send("setClipboard",Et({content:e,info:t,id:n,uuid:l.uuid}),r?()=>r():null)};return Et({GM_setClipboard:e?Et({value:t
}):void 0,"GM.setClipboard":e?Et({get:()=>i(t,2)}):void 0})})(),u=(()=>{let t=[];const o=e.storage;let r=0,i=null;const c=s(l.grant,lo),d=(e,t)=>{if("string"!=typeof e)return t;{const n=an(e,0,1);switch(e=an(e,1),n){case"b":return"true"===e;case"n":return xn(e);case"x":try{return So.decode(Ro.decode(e))}catch(t){return e}case"o":try{return Pt(e)}catch(e){Bn.log(`values: parseValueFromStorage: ${e}`)}return t;case"u":return;default:return e}}},u=(e,n,o,r)=>{n!=o&&Nt(t,(t=>{
if(t&&t.key==e&&t.cb)try{t.cb(e,d(n),d(o),r)}catch(t){Bn.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},g=(e,t)=>{i&&i.postMessage(Et({messageId:Kn(),method:"saveStorageKey",uuid:l.uuid,key:e,value:o.data[e],removed:t,id:n,ts:o.ts}))};c&&(No(n),i=Yn.connect("values",!0,!0),i.onDisconnect.addListener((()=>{Bn.warn("values: port disconnected"),i=null})),i.onMessage.addListener((e=>{if("ack"in e)return;const{storage:t,removed:n}=e;if(!t)return;const r=t,s=lt(r);n&&Ft(s,n),
Nt(s,(e=>{const t=o.data[e],n=r[e];void 0===n?delete o.data[e]:o.data[e]=n,u(e,t,n,!0)}))})),i.connectMessage(Et({messageId:Kn(),method:"addStorageListener",uuid:l.uuid,id:n})));const p=(e,t)=>d(o.data[e],t),m=()=>lt(o.data),f=(e,n)=>{const o=++r,s=Et({id:o,key:e,cb:n});return Ft(t,s),o},v=e=>{t=At(t,(t=>t.id!==e))},_=(e,t)=>{const n=o.data[e];o.ts=On(),o.data[e]=(e=>{const t=typeof e;let n,o=an(t,0,1);switch(t){case"object":try{n=o+xt(e)}catch(e){return void Bn.log(e)}break;case"function":
case"symbol":case"bigint":o="u",n=o+void 0;break;case"string":case"number":case"undefined":case"boolean":n=o+e;break;default:n=t}return n})(t),g(e),u(e,n,o.data[e],!1)},b=e=>{const t=o.data[e];o.ts=On(),delete o.data[e],g(e,!0),u(e,t,o.data[e],!1)};return Et({GM_getValue:c?Et({value:p}):void 0,"GM.getValue":c?Et({get:()=>a(p)}):void 0,GM_listValues:c?Et({value:m}):void 0,"GM.listValues":c?Et({get:()=>a(m)}):void 0,GM_addValueChangeListener:c?Et({value:f}):void 0,
"GM.addValueChangeListener":c?Et({get:()=>a(f)}):void 0,GM_removeValueChangeListener:c?Et({value:v}):void 0,"GM.removeValueChangeListener":c?Et({get:()=>a(v)}):void 0,GM_setValue:c?Et({value:_}):void 0,"GM.setValue":c?Et({get:()=>a(_)}):void 0,GM_deleteValue:c?Et({value:b}):void 0,"GM.deleteValue":c?Et({get:()=>a(b)}):void 0})})(),g=(()=>{const e=s(l.grant,wo),t=(()=>{let e=[],t=null;return Et({register:(o,r)=>{Ft(e,o),t||(No(n),t=Yn.connect("onurlchange",!0),t.onMessage.addListener((t=>{
if("ack"in t)return;const{url:n}=t;if(!n)return;const o=Et({url:n});Nt(e,(e=>{wt(e,r,[o])}))})),t.connectMessage(Et({messageId:Kn(),method:"observeUrlChanges",uuid:l.uuid,id:n})))},unregister:n=>{let o;n&&(o=Vt(e,n))>-1&&(e=Tt(e,o,1).result),t&&0===e.length&&(t.disconnect(),t=null)}})})();return Et({"window.onurlchange":e?Et({value:t}):void 0})})(),p=(()=>{const e=s(l.grant,go),t=e=>{for(let t=0;t<l.resources.length;t++){const n=l.resources[t];if(n.name==e){
if(n.error)Bn.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return So.decode(n.content)}catch(e){}return""}}return null},n=e=>{for(let t=0;t<l.resources.length;t++){const n=l.resources[t];if(n.name==e){if(n.error)Bn.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${Ro.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return Et({GM_getResourceText:e?Et({value:t}):void 0,
"GM.getResourceText":e?Et({get:()=>a(t)}):void 0,GM_getResourceURL:e?Et({value:n}):void 0,"GM.getResourceUrl":e?Et({get:()=>a(n)}):void 0})})(),m=(()=>{const e=s(l.grant,po),t=(e,t)=>{o.first.send("tabs",Et({action:"set",uuid:l.uuid,tab:e}),t?()=>t():null)},n=e=>{o.first.send("tabs",Et({action:"get",uuid:l.uuid}),e?t=>{e(t||Et({}))}:null)},r=e=>{o.first.send("tabs",Et({action:"list",uuid:l.uuid}),e?t=>{e(t||Et({}))}:null)};return Et({GM_saveTab:e?Et({value:t}):void 0,"GM.saveTab":e?Et({
get:()=>i(t,1)}):void 0,GM_getTab:e?Et({value:n}):void 0,"GM.getTab":e?Et({get:()=>i(n)}):void 0,GM_getTabs:e?Et({value:r}):void 0,"GM.getTabs":e?Et({get:()=>i(r)}):void 0})})(),f=(()=>{const e=s(l.grant,ho),o=e=>{const o=Kt(e);let s=!1,a=()=>{s=!0};const i=(e,t)=>{t=t||Et({}),e&&Ao((()=>{ut(t,r),wt(e,t,[t])}),1)},c=o.url;"object"==typeof c&&c.href&&(o.url=c.href);const d=(e,t)=>{const n=Jt(e);if("Blob"===n||"File"===n){const o=e;Lo(o).then((e=>{t(Et({type:n,value:e,meta:o.type,name:o.name,
lastModified:o.lastModified}))}))}else if("FormData"===n){const n=e,o=n.keys();let r;const s=Et({}),a=[];for(;!(r=o.next()).done;)Ft(a,r.value);const i=()=>{if(a.length){const e=Dt(a);let t=n.getAll(e);"[]"!==an(e,-2)&&(t=$n(t,0)),d(t,(t=>{s[e]=t,i()}))}else t(Et({type:"FormData",value:s}))};i()}else if("URLSearchParams"===n)t(Et({type:"URLSearchParams",value:En(e)}));else if("Array"===n||"Object"===n){const o=e;let r,s,a=0,i=0;if("Object"===n){const e=lt(o);s=t=>t<e.length?e[t]:null,r=Et({})
}else s=e=>e<o.length?e:null,r=[];const c=()=>{const e=s(a);null===e?t(Et({type:n,value:r})):d(o[e],(t=>{r[e]=t,a++,i++<1024?c():(i=0,Ao(c,1))}))};c()}else t(Et({value:e}))},u=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Go(e||"");else if("blob"==o)s=new Hn.Blob([t||Go(e||"")],Et({type:r}));else if("json"==o)s=Pt(e||"");else if("document"==o){const t=new Hn.DOMParser,n=["application/xhtml+xml","application/xml","image/svg+xml","text/html","text/xml"]
;let o=$n(Xt(r||"text/xml",";"),0);-1==Vt(n,o)&&(o="text/xml");try{s=mn(t,e||"",o)}catch(e){s=null}}else s=e||(t?(e=>{let t="";const n=new Dn(e);for(let e=0;e<n.length;e+=32687)t+=wt(sn,null,n.subarray(e,e+32687));return t})(t):"");return s};return(e=>{if(o.url){const t=an(o.url,0,5);if(-1!=Vt(["data:","blob:"],t))return e()}if(!o.data)return e();d(o.data,(t=>{o.binary&&(t.type="Blob"),o.data=t,o.data_type="typified",e()}))})((()=>{if(s)return s=!1,void i(o.onabort)
;let e,r,c,d=Yn.connect("xhr"),g=[],p=!1;const{method:m,url:f,redirect:v,headers:_,cookie:b,binary:h,nocache:M,revalidate:y,timeout:w,context:E,responseType:S,overrideMimeType:R,anonymous:G,cookiePartition:L,fetch:I,user:O,password:C,data:x,data_type:P}=o,k=Et({method:m,url:f,redirect:v,headers:_,cookie:b,binary:h,nocache:M,revalidate:y,timeout:w,responseType:S,overrideMimeType:R,anonymous:G,cookiePartition:L,fetch:I,user:O,password:C,data:x,data_type:P});if(k.headers){const e=k.headers
;Nt(lt(e),(t=>{"cookie"===un(t)&&(k.cookie=`${e[t]}`,delete e[t])}))}let T,D,A,U;d.postMessage(Et({messageId:Kn(),method:"xhr",details:k,callbacks:Et({onloadstart:!!o.onloadstart,onload:!!o.onload,ondone:!!o.onloadend,onreadystatechange:!!o.onreadystatechange,onerror:!0,onabort:!!o.onabort,ontimeout:!!o.ontimeout,onprogress:!!o.onprogress,onuploadprogress:!(!o.upload||!o.upload.onprogress),onpartial:!0}),id:n,location:Hn.location.href,uuid:l.uuid,no_blob:"js"==t.sandboxMode}));const $=S?un(S):""
;let j,F=0,V=0;const N=async t=>{if(t&&(c||void 0!==e||void 0!==r)){if(R?U=R:t&&(U=(e=>{const t=Et({});return e&&Nt(Xt(e,"\n"),(e=>{const n=Xt(e,":");if(n.length<2)return;const o=$n(n,0);if(!o)return;const r=$t(Ut(n,1),":");t[un(ln(o))]=ln(r||"")})),t})(t.responseHeaders)["content-type"]),T=e,c)A=c.stream;else if(r){const e=r;if(D=e.buffer,-1==Vt(["blob","arraybuffer"],$)&&!T){let t;kt([U,e.type],(e=>t=((e,t,n,o)=>{const r=cn(e,"charset=");if(-1==r)return;const s=an(e,r+8),a=cn(s,";")
;return-1==a?o&&o.optionalEnd?s:void 0:an(e,r+8,a)})(un(e||""),0,0,Et({optionalEnd:!0}))));const n=new Un([D]);j=Lo(n,t),T=await j}j=void 0}else j&&await j;e=r=void 0}if(T||A||D){t.responseType=S,Nt(["response_data"],(e=>delete t[e]));const e=Et({response:()=>u(T,D,A,$,U||"binary/octet-stream"),responseText:()=>u(T,D,A,"text",U),responseXML:()=>u(T,D,A,"document",U||"text/xml")});Nt(lt(e),(n=>{pt(t,n,Et({get(){try{return e[n]()}catch(e){Bn.warn(`${m}:`,e)}}}))}))}},q=[],X=async e=>{e&&Ft(q,e);{
const e=Dt(q);e&&e()}};"stream"===$&&X((async()=>{c=await Wn((e=>{const t=new Hn.ReadableStream(Et({start:n=>{Ao((()=>e(Et({stream:t,ctrl:n}))),0)},cancel:()=>{c&&(c.canceled||a(),c.canceled=!0)}}))}))})),d.onMessage.addListener((t=>X((()=>(async t=>{if(!("ack"in t))if(t.onpartial){const n=t.data,o=n,s=o.partial,a=n.nada;if(c){if(c.canceled)return;const e=on||((e,t)=>e.enqueue(t));if(void 0!==s)e(c.ctrl,s);else if(void 0!==a){const t=new Dn(a.buffer);e(c.ctrl,t)
}else Bn.error(`${m}:`,"data message without data?!")}else{let t;s&&Ft(g,s),a&&(t=a),void 0!==o.index&&o.index!==o.length-1||(g.length&&(e=$t(g,""),g=[]),r=t)}}else{const e=t.data;if(F=e.readyState||F,V=e.status||V,E&&(e.context=E),t.onload)await N(e),i(o.onreadystatechange,e),i(o.onload,e);else if(t.onreadystatechange)await N(e),4!=e.readyState&&i(o.onreadystatechange,e);else if(t.onerror)t.exception&&Bn.error(t.exception),i(o.onerror,e);else if(t.onabort)i(o.onabort,e);else if(t.ondone)p=!0,
c&&!c.canceled&&(rn||(e=>e.close()))(c.ctrl),await N(e),i(o.onloadend,e);else if(t.onloadstart)c&&await N(e),i(o.onloadstart,e);else if(t.onuploadprogress)o.upload&&i(o.upload.onprogress,e);else{const n=$n(At(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";i(o[n],e)}}})(t))))),d.onDisconnect.addListener((()=>{p||i(o.onerror,Et({readyState:F,status:V,error:"background shutdown"})),d=null})),a=()=>{d&&d.postMessage(Et({messageId:Kn(),cancel:!0}))}})),Et({abort:()=>{a()}})},r=(()=>{
const e=Et({DONE:Sn,HEADERS_RECEIVED:Rn,LOADING:Gn,OPENED:Ln,UNSENT:In});return Nt(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${gn(t)}`]=t})),e})();return Nt(lt(r),(e=>St(o,e,r[e]))),Et({GM_xmlhttpRequest:e?Et({value:o}):void 0,"GM.xmlHttpRequest":e?Et({get:()=>{const e=e=>c(o,e);return Nt(lt(r),(t=>St(e,t,r[t]))),e}}):void 0})})(),v=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{antifeatures:r,author:s,blockers:a,copyright:i,deleted:c,description_i18n:l,description:d,downloadURL:u,fileURL:g,grant:p,header:m,homepage:f,icon:v,icon64:_,lastModified:b,name_i18n:h,name:M,namespace:y,position:w,resources:E,supportURL:S,system:R,updateURL:G,version:L,webRequest:I,options:{override:{orig_connects:O,orig_excludes:C,orig_includes:x,orig_matches:P},run_at:k,unwrap:T}}=o,{downloadMode:D,inIncognitoContext:A,relaxedCsp:U,isFirstPartyIsolation:$,sandboxMode:j,userAgent:F,version:V}=t,N=G||g,q=Et({
antifeatures:r,author:s,blockers:a,connects:O,copyright:i,deleted:c,description_i18n:l,description:d,downloadURL:u,excludes:C,fileURL:g,grant:p,header:m,homepage:f,icon:v,icon64:_,includes:x,lastModified:b,matches:P,name_i18n:h,name:M,namespace:y,options:o.options,position:w,resources:E,"run-at":k,supportURL:S,system:R,unwrap:T,updateURL:G,version:L,webRequest:I}),X=Et({downloadMode:D,isFirstPartyIsolation:$,isIncognito:A,relaxedCsp:U,sandboxMode:j,script:q,scriptHandler:"Tampermonkey",
scriptMetaStr:o.header,scriptUpdateURL:N,scriptWillUpdate:!!N,userAgentData:F,version:V});n=X}return Pt(xt(n))};return Et({GM_info:Et({get:o}),"GM.info":Et({get:o})})})(),_=(()=>{const e=s(l.grant,Eo);let t=null;const o=(e,o)=>{const r=()=>{t==s&&(t=null),s=null};t&&t.disconnect(),No(n);let s=t=Yn.connect("webRequest",!0);return o&&s.onMessage.addListener((e=>{"ack"in e||o(e.type,e.message||"ok",e.details)})),s.onDisconnect.addListener(r),s.connectMessage(Et({messageId:Kn(),rules:e,uuid:l.uuid
})),Et({abort:()=>{s&&s.disconnect(),r()}})};return Et({GM_webRequest:e?Et({value:o}):void 0,"GM.webRequest":e?Et({get:()=>a(o)}):void 0})})(),b=(()=>{const e=s(l.grant,_o);let t=0;const n=Et({}),o=Et({}),r=(e,r,s)=>{if("string"!=typeof e)throw"invalid name";const{accessKey:a,autoClose:c,title:d,id:u}="string"==typeof s?Et({accessKey:s}):s||Et({}),g=void 0!==u?u:++t,p=n[g],m=p||Yn.connect("registerMenuCommand",!0);return o[g]=r,p||(m.onMessage.addListener((e=>{if(!("ack"in e)&&"run"===e.method){
const t=o[g];if(!t)return;const n=e.event,r=n?n.keyCode?new kn("keypress",n):new Tn("click",e.event):void 0;Ao((()=>t(r)),1)}})),m.onDisconnect.addListener((()=>{i(g)})),n[g]=m),m.connectMessage(Et({messageId:Kn(),name:e,uuid:l.uuid,createdAt:On(),accessKey:a,autoClose:c,title:d,id:`${g}`})),g},i=e=>{delete o[e];const t=n[e];t&&(t.disconnect(),delete n[e])};return Et({GM_registerMenuCommand:e?Et({value:r}):void 0,"GM.registerMenuCommand":e?Et({get:()=>a(r)}):void 0,
GM_unregisterMenuCommand:e?Et({value:i}):void 0,"GM.unregisterMenuCommand":e?Et({get:()=>a(i)}):void 0})})(),h=(()=>{const e=s(l.grant,fo),t=(e,t,n,o)=>{let r,s,a=null;const i=e=>$t([e?`tag-${e}`:Kn(),l.uuid],"#");if("object"==typeof e){const n=e,{timeout:c,text:d,image:u,title:g,highlight:p,silent:m,url:f,tag:v}=n;s=i(v),r=Et({id:s,timeout:c,text:d,image:u||l.icon64||l.icon||void 0,title:g||l.name,highlight:p,silent:m,url:f,tag:v}),a=n.ondone,o=n.onclick,"function"==typeof t&&(a=t)}else s=i(),
r=Et({id:s,text:e,title:"string"==typeof t?t:l.name,image:n||l.icon64||l.icon||void 0});r.onclick=o,r.ondone=a||void 0,((e,t)=>{const{text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d,onclick:u,ondone:g}=Kt(t);if(n||i){const t="notification",p=Yn.connect(t,!0);p.onMessage.addListener((e=>{if("ack"in e)return;const{clicked:t}=e;let l=!1;const m=Et({text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d,preventDefault:()=>{l=!0}});t&&(u&&u(m),p.postMessage(Et({
messageId:Kn(),canceled:l}))),g&&g(!0===t,m),p.disconnect()})),p.connectMessage(Et({messageId:Kn(),method:"notification",id:e,uuid:l.uuid,text:n,title:o,tag:r,url:s,image:a,highlight:i,silent:c,timeout:d}))}else Bn.warn("GM_notification: neither a message text nor highlight options were given!")})(s,r)};return Et({GM_notification:e?Et({value:t}):void 0,"GM.notification":e?Et({get:()=>(e,n,o,r)=>{let s;return s="object"==typeof e?e:Et({text:e,title:n,image:o,onclick:r}),new Hn.Promise((e=>{
const n=Et({});Nt(lt(s),(e=>{n[e]=s[e]}));const o=n.ondone;n.ondone=function(t,n){o&&wt(o,this,[t,n]),wt(e,this,[t])},t(n)}))}}):void 0})})(),M=(()=>{const e=s(l.grant,co),t=(e,t)=>Et({action:e,uuid:l.uuid,location:Hn.location.href,details:t}),n=Et({set:(e,n)=>{o.first.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{o.first.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{o.first.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return Et({
GM_cookie:e?Et({get:()=>{const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return Nt(lt(n),(t=>{St(e,t,n[t])})),e}}):void 0,"GM.cookie":e?Et({get:()=>{const e=Et({});return Nt(lt(n),(t=>{e[t]=e=>((e,t)=>new Hn.Promise(((o,r)=>{if("list"==e){const s=t;n[e](s,((e,t)=>{t?r(t):o(e)}))}else if("set"==e){const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}else{const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}})))(t,e)})),e}}):void 0})})(),y=(()=>{const e=s(l.grant,uo),t=(e,t)=>"object"==typeof e?e:Et({url:e,name:t,
headers:void 0,saveAs:void 0,conflictAction:void 0,onprogress:void 0,onload:void 0,ondone:void 0,ontimeout:void 0,onerror:void 0}),o=(e,o)=>{const r=t(e,o),s=(e,t)=>{t=t||Et({}),e&&Ao((()=>{wt(e,t,[t])}),1)},{url:a,name:i,headers:c,saveAs:d,conflictAction:u}=r;let g;No(n);let p=Yn.connect("download",!0);const m=()=>{p&&p.stopReconnecting()};p.onMessage.addListener((e=>{if(!("ack"in e)){p&&void 0===g&&(g=e.id,p.connectMessage(Et({messageId:Kn(),method:"download",uuid:l.uuid,id:g}),!1));try{
e.load?(r.onload&&s(r.onload,e.data),m()):e.progress?r.onprogress&&s(r.onprogress,e.data):e.timeout?(r.ontimeout&&s(r.ontimeout,e.data),m()):(r.onerror&&s(r.onerror,e.data),m())}catch(e){Bn.log("env: Error: TM_download - ",e,r)}}})),p.onDisconnect.addListener((()=>p=null));const f=Et({messageId:Kn(),details:Et({url:a,name:i,headers:c,conflictAction:u,saveAs:d}),uuid:l.uuid});return p.postMessage(f),Et({abort:()=>{p&&p.postMessage(Et({uuid:l.uuid,cancel:!0}))}})};return Et({GM_download:e?Et({
value:o}):void 0,"GM.download":e?Et({get:()=>(e,n)=>c(o,t(e,n))}):void 0})})(),w=(()=>{const e=s(l.grant,vo),t=(e,t)=>{const o="openInTab";let r,s,a=!1,i=null;const c=(()=>{const e=[];return Et({run:t=>{if(t&&Ft(e,t),r)for(;e.length;)Dt(e)()}})})();No(n);let d=Yn.connect(o,!0);const u=()=>{d&&d.postMessage(Et({messageId:Kn(),close:!0}))};d.onMessage.addListener((e=>{"ack"in e||(e.tabId?a?u():(d&&void 0===r&&d.connectMessage(Et({messageId:Kn(),method:o,uuid:l.uuid,tabId:e.tabId}),!1),r=e.tabId,
c.run()):e.name?s=e.name:e.closed&&(a=!0,i&&(i(),i=null),d&&d.stopReconnecting()))})),d.onDisconnect.addListener((()=>d=null)),d.postMessage(Et({messageId:Kn(),method:o,url:e,location:Hn.location.href,options:t,uuid:l.uuid}));const g=Et({});return gt(g,Et({close:Et({value:()=>{a?Bn.warn("env: attempt to close already closed tab!"):u()}}),focus:Et({value:()=>{d&&d.postMessage(Et({messageId:Kn(),focus:!0}))}}),closed:Et({get:()=>a}),onclose:Et({get:()=>i,set:e=>{i=e}}),name:Et({get:()=>s,set:e=>{
c.run((()=>{d&&d.postMessage(Et({messageId:Kn(),name:e}))}))}})})),g};return Et({GM_openInTab:e?Et({value:t}):void 0,"GM.openInTab":e?Et({get:()=>a(t)}):void 0})})(),E=(()=>{const e=s(l.grant,Mo);return Et({"window.close":e?Et({value:e=>{o.first.send("closeTab",Et({uuid:l.uuid}),e?()=>e():null)}}):void 0})})(),S=(()=>{const e=s(l.grant,yo);return Et({"window.focus":e?Et({value:e=>{o.first.send("focusTab",Et({uuid:l.uuid}),e?()=>e():null)}}):void 0})})(),R=(()=>{
const e=s(l.grant,mo),t=function(...e){wt(Bn.log,this,e)};return Et({GM_log:e?Et({value:t}):void 0,"GM.log":e?Et({get:()=>a(t)}):void 0})})(),G=({root:e,tag:t,properties:n,cb:r})=>{const s=Kn(),a=Et({tag:t,properties:n,id:s,uuid:l.uuid});o.first.send("addElement",a,e,r?()=>r():null);const i=Fn.getElementById(s),c=n?n.id:void 0;return void 0!==c&&bn(i,"id",c),i},L=(()=>{const e=s(l.grant,io),t=(e,t)=>G(Et({root:void 0,tag:"style",properties:Et({textContent:e}),cb:t}));return Et({
GM_addStyle:e?Et({value:t}):void 0,"GM.addStyle":e?Et({get:()=>a(t)}):void 0})})(),I=(()=>{const e=s(l.grant,io),t=(e,t,n,o)=>{let r,s,a,i;return"string"==typeof e?(s=e,a=t,i=n):(r=e,s=t,a=n,i=o),a&&(a=Et(a)),G(Et({root:r,tag:s,properties:a,cb:i}))};return Et({GM_addElement:e?Et({value:t}):void 0,"GM.addElement":e?Et({get:()=>a(t)}):void 0})})(),O=(()=>{const e=s(l.grant,ao),t=(e,t)=>{const o="backgroundControl",r=Yn.connect(o);let s=!1;const a="restart"===e.action||void 0
;r.onMessage.addListener((e=>{if("ack"in e)return;s=!0;const n=e?e.error:void 0;n&&Bn.warn(n),t&&t(n),r.disconnect()})),r.postMessage(Et({messageId:Kn(),method:o,id:n,uuid:l.uuid,restart:a})),a&&(Vo=!1),r.onDisconnect.addListener((()=>{!s&&t&&t(a?void 0:"port disconnected for unknown reason"),s=!0}))};return Et({"GM.backgroundControl":e?Et({get:()=>a(t)}):void 0})})(),C=Et({...I,...L,...E,...M,...y,...S,...v,...R,...b,...h,...w,...p,...d,...m,...g,...u,..._,...f,...O})
;return r[e.script.uuid]=r[e.script.uuid]||C,r[e.script.uuid]}})},Xo=(e,t,n,o,r,s)=>{const a=(e,t,n,o,r)=>{const a=t[n],i=typeof a;return o&&"string"===i?t[n]=()=>s(a,r):r&&"function"===i&&(t[n]=function(){return wt(a,r,arguments)}),wt(e,qn,t)};let i=!0;Jn((()=>i=!1));const c=Et({}),l=e=>!!("object"==typeof e&&null!==e?e.capture:e),d=(e,o,r)=>{let d,g;null===o||("object"==typeof o?(d=async e=>{const t=o.handleEvent;"function"==typeof t&&wt(t,o,[e])},g=o):(d=o,g=void 0));const m=l(r);let f,v
;if(void 0!==d&&i&&((f="DOMContentLoaded"==e)||"load"==e)){const n=vn(qn.document);if(f&&("complete"==n||"interactive"===n)&&"document-idle"!=t||!f&&"complete"==n)return void(async(e,t,n,o)=>{const r=Et({attrName:"null",newValue:"null",prevValue:"null",eventPhase:Mn,target:qn.document,relatedNode:qn.document,srcElement:qn.document});await null,n||await null,"load"===e&&await null,((e,t,n,o)=>{const r=Et({bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,
defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:On()}),a="string"==typeof n?()=>s(n,o):n,i=new Event(e);Nt(lt(r),(e=>{St(i,e,r[e])})),Nt(lt(t),(e=>{St(i,e,t[e])})),wt(a,o,[i])})(e,r,t,o)})(e,d,m,p)}const _="urlchange"==e?n["window.onurlchange"]:void 0;if(void 0===d);else if("string"!=typeof d){const t=`${e}-${m}`;c[t]=c[t]||[];const n=function(...t){return"object"==typeof r&&r.once&&u(e,o,r),
wt(d,this===qn||this===Xn?p:this,t)},s=Et({listener:d,filter:n,object:g});if(Ft(c[t],s),v=n,_)return void _.value.register(n)}else{if(_)return void Bn.warn("env: urlchange listener must be a function!");v=d}return a(Hn.addEventListener,[e,v,r],1,!0)},u=(e,t,o)=>{let r,s;null===t||("object"==typeof t?s=t:r=t);const i="urlchange"==e?n["window.onurlchange"]:void 0,d=l(o),u=`${e}-${d}`,g=c[u]&&At(c[u],(e=>e.object?e.object===s:e.listener===r));if(g&&g.length){let t;if(Nt(g,(n=>{
if(i)i.value.unregister(n.filter);else try{a(Hn.removeEventListener,[e,n.filter,o],1,!0)}catch(n){t=n}const r=Vt(c[u],n);c[u]=Tt(c[u],r,1).result})),c[u].length||delete c[u],t)throw t}else if(void 0!==r)return a(Hn.removeEventListener,[e,r,o],1,!0)},g=Et({CDATA:Et({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:Et({value:e=>{try{return`\\$1 = ${xt(e)};`}catch(e){Bn.log(e)}}}),define:Et({value:void 0}),module:Et({value:void 0}),
exports:Et({value:void 0}),setTimeout:Et({value:(...e)=>a(jo,e,0,!0,p)}),setInterval:Et({value:(...e)=>a(Fo,e,0,!0,p)}),close:(()=>{const e=n["window.close"];return e?Et({get:()=>qn==qn.top?t=>e.value(t):Hn.close}):void 0})(),focus:(()=>{const e=n["window.focus"];return e?Et({get:()=>t=>e.value(t)}):void 0})(),onurlchange:n["window.onurlchange"]?(()=>{let e=null;return Et({get:()=>e,set:t=>{e&&u("urlchange",e),e=t,d("urlchange",e)}})})():void 0,location:Et({set:e=>{Hn.location.href=e}}),
name:Et({get:()=>qn.name,set:e=>{qn.name=e}}),clearInterval:Et({get:()=>$o}),clearTimeout:Et({get:()=>Uo}),addEventListener:Et({value:d}),removeEventListener:Et({value:u}),console:Et({get:()=>eo})});if(!e){const e=Et({window:Et({get:()=>p}),globalThis:Et({get:()=>p}),cloneInto:Et({value:e=>e}),exportFunction:Et({value:(e,t,n)=>{const o=n&&Rt(n,"defineAs");return o&&(t[o]=e),e}}),createObjectIn:Et({value:(e,t)=>{const n=Et({}),o=t&&Rt(t,"defineAs");return o&&(e[o]=n),n}}),undefined:Et({get:()=>{}
})});ut(g,e)}o&&ut(g,o);const p=r(g);return p};let Bo;(async()=>{const n=e.contextId;let o;const{fSend:r,fOnMessage:s,cloneInto:a,pageWindow:i}=e;o=r&&s?(({sendPrefix:e,listenPrefix:t,send:n,onMessage:o})=>{if(void 0===n||void 0===o)throw"invalid args";let r,s,a=1;const i=Et({}),c=Et({}),l=e=>{e&&(r=e)},d=e=>{const t=++a;return c[a]=e,t};o(((o,a)=>o==`${t}_${r}`?(t=>{const{m:o,r:a,a:l,n:d}=t;if(i[o]&&(Nt(i[o],(e=>e(l))),delete i[o]),"message.response"==o){if(null==a)throw"Invalid Message"
;((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(a,l)}else if(s){const t=a?t=>{n(`${e}_${r}`,Et({m:"message.response",a:t,r:a}))}:()=>{};s(Et({method:o,args:l,node:d}),t)}})(a):null));const u=Et({init:async e=>{r?l():l(e)},refresh:()=>null,switchId:e=>{r&&u.cleanup(),l(e)},send:(t,o,s,a)=>Wn((i=>{let c,l;"function"!=typeof s&&null!==s?(c=s,l=a):l=s,n(`${e}_${r}`,Et({m:t,a:o,r:l?d(l):null,n:c})),i()})),sendToId:(t,o,r)=>{n(`${e}_${t}`,Et({m:o,a:r,r:null}))},once:(e,t)=>{i[e]||(i[e]=[]),
Ft(i[e],t)},setMessageListener:e=>{s=e},cleanup:()=>null});return u})(Et({sendPrefix:"2U",listenPrefix:"2S",send:r,onMessage:s})):(({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const r=e=>o?o(e,qn.document):e,s=Et({});let a,i,c=1;const l=Et({});let d=!1,u=[];const g=()=>{b=qn.document.documentElement,d=!1;const e=u;u=[],Nt(e,(e=>{d||M()?Ft(u,e):e()}))};let p;const m=e=>{const t=++c;return l[c]=e,t},f=(e,t)=>{const{m:n,a:o,r:s,n:a}=t,{m:i,c}=((e,t,n)=>{let o,s;return n?(s=new Tn(e,Et({
relatedTarget:n})),o=new Pn(e,Et({detail:r(t)}))):o=new Pn(e,Et({detail:r(t)})),Et({m:s,c:o})})(e,Et({m:n,a:o,r:s}),a);i&&wt(De,qn,[i]),wt(De,qn,[c])},v=t=>{const n=(e=>{if("MouseEvent"===Jt(e)){const t=yn(e);if(!t)throw"Invalid MouseEvent";return void(p=t)}const t=Kt(wn(e));return p&&(t.n=p,p=void 0),t})(t);if(!n)return;const{m:o,r,a:c,n:d}=n;if(s[o]&&(Nt(s[o],(e=>e(c))),delete s[o]),"unlock"==o)f(`${e}_${i}`,Et({m:"unlocked",a:void 0,r:null})),
g();else if("unlocked"==o)g();else if("message.response"==o){if(null==r)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(r,c)}else if(a){const t=r?t=>{f(`${e}_${i}`,Et({m:"message.response",a:t,r}))}:()=>{};a(Et({method:o,args:c,node:d}),t)}},_=e=>{e&&(i=e),i&&Hn.addEventListener(`${n}_${i}`,v,!0)};let b,h;const M=()=>{if((()=>{const e=qn.document.documentElement;return b||(b=e),b!==e})()){if(h){const e=h;h=void 0,e(qn.document)}return!0}},y=Et({init:async(n,o)=>{
i?_():_(n),(e=>(b=qn.document.documentElement,Wn((async n=>{if(h=n,t&&!e&&(await null,M()))return;const o=new An((()=>{M()&&o.disconnect()}));o.observe(qn.document,Et({childList:!0}))}))))(o).then((()=>{d=!0,y.refresh(),f(`${e}_${i}`,Et({m:"unlock",a:void 0,r:null}))}))},refresh:()=>{const e=i;e&&(y.cleanup(),y.init(e,!0))},switchId:e=>{i&&y.cleanup(),_(e)},send:(t,n,o,r)=>Wn((s=>{let a,c;"function"!=typeof o&&null!==o?(a=o,c=r):c=o,M();const l=()=>{f(`${e}_${i}`,Et({m:t,a:n,r:c?m(c):null,n:a
})),s()};d?Ft(u,l):l()})),sendToId:(t,n,o)=>{f(`${e}_${t}`,Et({m:n,a:o,r:null}))},setMessageListener:e=>{a=e},once:(e,t)=>{s[e]||(s[e]=[]),Ft(s[e],t)},cleanup:()=>{i&&(Hn.removeEventListener(`${n}_${i}`,v,!0),i=void 0)}});return y})(Et({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=o;const c=ut(e.console,Zn);o.init(n);const l=Et({});o.setMessageListener((({method:t,args:n})=>{if("commid"==t)o.switchId(n.id),o.send("ack",Et({id:n.id}));else if("injectable"==t)g(n.id,(()=>{o.send("ack",Et({
id:n.id}))})),o.send("injectableack",Et({id:n.id}));else if("setForeignAttr"==t)qn[n.attr]=n.value;else if("script"==t){const{id:t,unwrap:r,bundle:s}=n,{script:a}=s,{name:i,uuid:c,options:{run_at:u}}=a;g(t,(t=>{const o=r?()=>t():()=>wt(t,((t,n,o,r)=>{const{pageWindow:s,cloneInto:a,exportFunction:i}=e,c=s||qn,{script:l}=t,d=l.options.compat_powerful_this,u=-1!==Vt(l.grant,"none");Bo=Bo||qo(n);const g=Bo.of(t),p=e=>Et({p:v,r:wt,s:e}),m=Et({seed:Et({get:()=>p(b),once:!0})}),f=Et({}),v=Et({GM:f
}),_=c&&c;d&&(St(m,"GM",Et({value:f})),St(m,"unsafeWindow",Et({value:_}))),u||(v.unsafeWindow=_),Nt(lt(g),(e=>{const t=an(e,0,3),n=g[e];if(void 0!==n)if("GM_"===t)v[e]=void 0!==n.get?n.get():n.value,d&&St(m,e,n);else if("GM."===t){const t=Bt(e,3);pt(f,t,n)}}));const b=u?p(d?v:Et({})):Xo(u,l.options.run_at,g,m,o,r);return b})(s,n.flags,d,p),[]);"document-start"==u||"context-menu"==u?o():l[c]=o})),o.send(`scriptack-${t}`,Et({id:t}))
}else if("port.message"==t)Yn.message(n,o);else if("external.connect"==t)(t=>{const{bridges:n}=e,o=qn,r=Rt(o,"external");if(!r)return;const s=t?e=>t(e,o,Et({cloneFunctions:!0})):e=>e,a=(e,t)=>{n.first.send("external.message",e,t)};try{const e=()=>{const e=Et({getVersion:e=>{a(Et({method:"getVersion"}),(t=>e(s(t))))},openOptions:(e,t)=>{a(Et({method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),a(Et({method:"isInstalled",script:Et({name:e,namespace:t})
}),(e=>n(s(e))))}});return s(e)};gt(r,Et({Tampermonkey:Et({value:e(),configurable:!0})}))}catch(e){}})(a);else if("run"==t){const{uuid:e}=n,t=Rt(l,e);t?"function"==typeof t&&(t(),delete l[e]):c.warn(`env: missing script "${e}"!`)}}));const{createProxy:d}=((e,t)=>{const n=(e=>{let t=Et({});const n=(e,o,r)=>{const s=vt(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=ut(t,_t(e)))};return n(e,null,5),t})(qn);Nt(so,(e=>delete n[e]));const o=n;return Et({createProxy:n=>{let r=o;const s=e=>{let t,n
;const o=(t=ft(p,e))||(n=r[e]);return Et({d:o?Et(o):o,l:!!t,w:!!n})},a=e=>{if(!c(e))return!1;if("length"===e)return!0;const t=ht(xn(e));return t>=0&&t<=Yt&&e===`${t}`},i=e=>"on"===an(e,0,2),c=e=>"string"==typeof e,l=(e,n)=>{const o=an(e,2),r=g[o];if(r&&(t.removeEventListener(o,r),delete g[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>wt(n,t,e);t.addEventListener(o,e),g[o]=e}},d=t=>void 0!==t&&(t===e||t===qn||t===Xn),u=Et({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,
cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,dispatchEvent:!0,dump:!0,fetch:!0,find:!0,focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,
scrollBy:!0,scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,showDirectoryPicker:!0,sizeToContent:!0,stop:!0,structuredClone:!0,updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});Nt(lt(u),(e=>{n[e]=n[e]||Et({bind:!0})}));const g=Et({}),p=Et({});St(p,pn,"Window");const m=new Cn(p,Et({defineProperty:(e,t,o)=>{const{d:r,l:d}=s(t),u=Et(o)
;return r&&!r.configurable&&(!!r.configurable!=!!u.configurable||!!r.enumerable!=!!r.enumerable)||a(t)?(pt(d?p:qn,t,u),!1):(pt(p,t,u),c(t)&&i(t)&&l(t),delete n[t],!0)},deleteProperty:(e,t)=>{let{d:a,l:d,w:u}=s(t);return!(!a||!a.configurable)&&(d&&(d=delete p[t],c(t)&&i(t)&&l(t)),(u||(a=r[t])&&a.configurable)&&(o===r&&(r=ut(Et({}),o)),u=delete r[t]),delete n[t],d||u)},get:(e,t)=>{const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:i}=a(t)?Et({
d:ft(qn,t),l:!1}):s(t);if(r){let e;const n="value"in r?Rt(r,"value"):(e=Rt(r,"get"))&&"function"==typeof e?i?e():Ct(e,qn)():void 0;return n&&o&&o.bind?Ct(n,qn):i||"event"==t?n:d(n)||"globalThis"===t?m:n}},getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return Et({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!a(t))return;o=ft(qn,t),r=!1}const i=ut(Et({}),o);if(d(i.value)&&(i.value=m),!r){const e=i.get;e&&(i.get=()=>{
const t=Ct(e,qn)();return d(t)?m:t}),i&&!i.configurable&&pt(p,t,i)}return i},has:(e,t)=>t in p||t in n||t in r,ownKeys:()=>{const e=e=>!(e in r),t=lt(r),n=At(lt(_t(p)),e),o=Et({});for(let e=0;"Window"===Jt(Gt(qn,e));e+=1)o[e]=!0;const s=At(lt(o),e);return jt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d}=s(t);return!(d&&!d.writable&&!Rt(d,"set")||a(t)||(delete n[t],St(p,t,o),c(t)&&i(t)&&l(t,o),0))}}));return m}})})(i,Hn),u=e=>{
o.send("csp",Et({src:e}))},g=async(e,t)=>{pt(Xn,e,Et({set:n=>(delete Xn[e],zn(),t(n)),configurable:!0,enumerable:!1})),Jn((()=>delete Xn[e]))},p=(e,t)=>t?((e,t)=>{const n=`__p__${Kn()}`;(async(e,t)=>{g(e,(e=>wt(e,t,[])))})(n,t),u('window["'+n+'"] = function(){'+e+"};"),delete Xn[n]})(e,t):u(e)})(),zn()})()};